# Generated by Django 4.1.2 on 2022-11-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=50)),
                ('writers', models.CharField(max_length=50)),
                ('storyline', models.TextField()),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
